[project]
name = "agentflow-backend"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.121.0",
    "python-dotenv>=1.2.1",
    "uvicorn[standard]>=0.38.0",
]
